services:
  db:
    image: postgres:15
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
  web:
    build:
      context: .
    volumes:
      - .:/web
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
